# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: air-to-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: prod
  profile: private-sls
  deploymentBucket:
    name: deployment.iot.click


functions:
  iotclick:
    handler: handler.air
    environment:
      BUCKET: sambot-air
      ROOMS: studio,guest,livingroom,johann,bedroom
    tags: # Function specific tags
      project: sambot
      sambot: air
